services:
  - type: web
    name: dusttown-rp-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://dusttown-rp-render-6.onrender.com/?view=miniapp
      - key: TELEGRAM_BOT_TOKEN
        sync: false
